version: '3.4'

services:
  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: src/Inventory.API/Dockerfile
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
